project_id = "imwastdmyeaaslurcovw"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://imwastdmyeaaslurcovw.lovableproject.com"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[db]
port = 54322

[edge_functions]
region = "us-east-1"
inspector_port = 8083

[functions.geocode]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = true

[functions.create-donation-payment]
verify_jwt = false

[functions.cleanup-old-events]
verify_jwt = true

[functions.schedule-cleanup]
verify_jwt = true

[functions.trigger-cleanup]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.get-visitor-location]
verify_jwt = false

[functions.send-event-notification]
verify_jwt = true

[functions.indexnow]
verify_jwt = false

[functions.create-ticket-payment]
verify_jwt = false

[functions.handle-ticket-webhook]
verify_jwt = false

[functions.send-contact-notification]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
